/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controller.DatosProdControlador;
import Controller.ProductorControlador;
import DAO.ComunaDAO;
import DTO.Comuna;
import DTO.Direccion;
import DTO.Productor;
import DTO.Usuario;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge
 */
public class DatosProductor extends javax.swing.JFrame {

    DatosProdControlador dpc = new DatosProdControlador();
    ComunaDAO cdao = new ComunaDAO();
    Productor pro = new Productor();

    /**
     * Creates new form Ventana_Principal
     *
     * @param usu
     */
    public DatosProductor(Usuario usu) {
        initComponents();
        this.setTitle("Editar datos personales");
        ArrayList<Comuna> arrcomuna = cdao.listaComunas();
        pro = dpc.getProductor(usu.getRut());
        DefaultComboBoxModel modelComunaCom = new DefaultComboBoxModel(arrcomuna.toArray());
        DefaultComboBoxModel modelComunaPar = new DefaultComboBoxModel(arrcomuna.toArray());
        cbComunaCom.setModel(modelComunaCom);
        cbComunaPart.setModel(modelComunaPar);
        txtRut.setText(pro.getRut());
        txtRut.setEnabled(false);
        txtDv.setText(pro.getDv());
        txtDv.setEnabled(false);
        txtNombre.setText(pro.getNombre());
        txtNombre.setEnabled(false);
        txtApellido.setText(pro.getApellido());
        txtApellido.setEnabled(false);
        txtCorreo.setText(pro.getCorreo());
        txtCorreo.setEnabled(false);
        txtDireccioncomercial.setText(pro.getDireccion_negocio());
        txtDireccioncomercial.setEnabled(false);
        txtNumerocomercial.setText(pro.getNumero_negocio());
        txtNumerocomercial.setEnabled(false);
        txtDireccionparticular.setText(pro.getDireccion_particular());
        txtDireccionparticular.setEnabled(false);
        txtNumeroparticular.setText(pro.getNumero_particular());
        txtNumeroparticular.setEnabled(false);
        if (pro.getSexo().compareTo("M") == 0) {
            rbnMasculino.setSelected(true);
        }
        if (pro.getSexo().compareTo("F") == 0) {
            rbnFemenino.setSelected(true);
        }
        rbnFemenino.setEnabled(false);
        rbnMasculino.setEnabled(false);
        txtTelefono.setText(pro.getTelefono());
        txtTelefono.setEnabled(false);
        Comuna comn = new Comuna();
        comn.setNombre(pro.getComuna_negocio());
        comn.setId_comuna(Integer.parseInt(pro.getId_comunanegocio()));
        cbComunaCom.setSelectedItem(comn);
        Comuna comp = new Comuna();
        comp.setNombre(pro.getComuna_particular());
        comp.setId_comuna(Integer.parseInt(pro.getId_comunaparticular()));
        cbComunaPart.setSelectedItem(comp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDireccionparticular = new javax.swing.JTextField();
        txtDireccioncomercial = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtDv = new javax.swing.JTextField();
        rbnMasculino = new javax.swing.JRadioButton();
        rbnFemenino = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        txtNumeroparticular = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNumerocomercial = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtPassword1 = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        txtPassword2 = new javax.swing.JPasswordField();
        cbComunaPart = new javax.swing.JComboBox();
        cbComunaCom = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("MODIFICAR DATOS");

        jLabel3.setText("RUT:");

        jLabel4.setText("NOMBRE:");

        jLabel5.setText("APELLIDOS:");

        jLabel6.setText("SEXO:");

        jLabel7.setText("DIRECCIÓN PARTICULAR:");

        jLabel8.setText("TELÉFONO:");

        jLabel9.setText("CORREO:");

        jLabel10.setText("DIRECCIÓN COMERCIAL:");

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("-");

        buttonGroup1.add(rbnMasculino);
        rbnMasculino.setText("MASCULINO");

        buttonGroup1.add(rbnFemenino);
        rbnFemenino.setText("FEMENINO");

        jLabel12.setText("NÚMERO:");

        jLabel13.setText("COMUNA:");

        jLabel14.setText("NÚMERO:");

        jLabel15.setText("COMUNA:");

        jLabel16.setText("NUEVA CONTRASEÑA:");

        jLabel17.setText("CONFIRMAR CONTRASEÑA:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(rbnMasculino)
                                .addGap(33, 33, 33)
                                .addComponent(rbnFemenino))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 92, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnModificar)
                                .addGap(247, 247, 247)
                                .addComponent(btnVolver))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtDv, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCorreo))
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDireccionparticular, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNumeroparticular, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbComunaPart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDireccioncomercial, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNumerocomercial, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel15)
                                        .addGap(10, 10, 10)
                                        .addComponent(cbComunaCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(126, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtDv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rbnMasculino)
                    .addComponent(rbnFemenino))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDireccionparticular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtNumeroparticular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(cbComunaPart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtDireccioncomercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtNumerocomercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(cbComunaCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnVolver))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_btnVolverActionPerformed


    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        if (btnModificar.getText().compareTo("MODIFICAR") == 0) {
            btnModificar.setText("GUARDAR");
//            txtRut.setEnabled(true);
//            txtDv.setEnabled(true);
            txtNombre.setEnabled(true);
            txtApellido.setEnabled(true);
            txtCorreo.setEnabled(true);
            txtDireccioncomercial.setEnabled(true);
            txtNumerocomercial.setEnabled(true);
            txtDireccionparticular.setEnabled(true);
            txtNumeroparticular.setEnabled(true);
            rbnFemenino.setEnabled(true);
            rbnMasculino.setEnabled(true);
            txtTelefono.setEnabled(true);
        } else {
            if (btnModificar.getText().compareTo("GUARDAR") == 0) {
                String rut = txtRut.getText().trim();
                String dv = txtDv.getText().trim();
                String nombre = txtNombre.getText();
                String apellido = txtApellido.getText();
                String correo = txtCorreo.getText();
                String dirComercial = txtDireccioncomercial.getText();
                String numeroComercial = txtNumerocomercial.getText();
                String comunaComercial = Integer.toString(((Comuna) cbComunaCom.getSelectedItem()).getId_comuna());
                String dirParticular = txtDireccionparticular.getText();
                String numeroParticular = txtNumeroparticular.getText();
                String comunaParticular = Integer.toString(((Comuna) cbComunaPart.getSelectedItem()).getId_comuna());
                String sexo = "";
                String mismaDireccion = "";
                if (rbnMasculino.isSelected()) {
                    sexo = "M";
                } else {
                    if (rbnFemenino.isSelected()) {
                        sexo = "F";
                    } else {
                        JOptionPane.showMessageDialog(null, "DEBE SELECCIONAR SEXO");
                    }
                }
                String telefono = txtTelefono.getText();
                if (dirComercial.compareToIgnoreCase(dirParticular) == 0 & numeroComercial.compareToIgnoreCase(numeroParticular) == 0
                        & comunaComercial.compareToIgnoreCase(comunaParticular) == 0) {
                    mismaDireccion = "1";
                } else {
                    mismaDireccion = "0";
                }

                Productor produc = new Productor(rut, dv, nombre, apellido, sexo,
                        pro.getId_direccion_negocio(), pro.getId_direccion_particular(),
                        dirParticular, numeroParticular, comunaParticular,
                        telefono, correo, dirComercial, numeroComercial,

                        comunaComercial, mismaDireccion, pro.getId_comunanegocio(),
                        pro.getRegioncomercial(), pro.getId_comunaparticular(), pro.getRegionparticular());


                Direccion dirPart = new Direccion();
                Direccion dirCom = new Direccion();
                //Actualizamos dirección particular
                dirPart.setId_comuna(Integer.parseInt(comunaParticular));
                dirPart.setNombre(dirParticular);
                dirPart.setNumero(numeroParticular);
                dirPart.setId_direccion(Integer.parseInt(pro.getId_direccion_particular()));
                dirPart.setCoordenadaX("0");
                dirPart.setCoordenadaY("0");
                //Actualizamos dirección comercial
                dirCom.setId_comuna(Integer.parseInt(comunaComercial));
                dirCom.setNombre(dirComercial);
                dirCom.setNumero(numeroComercial);
                dirCom.setId_direccion(Integer.parseInt(pro.getId_direccion_negocio()));
                dirCom.setCoordenadaX("0");
                dirCom.setCoordenadaY("0");

                if (dpc.Update(produc) && dpc.UpdateDireccion(dirPart) && dpc.UpdateDireccion(dirCom)) {
                    JOptionPane.showMessageDialog(null, "DATOS MODIFICADOS EXITOSAMENTE");
                } else {
                    JOptionPane.showMessageDialog(null, "HUBO UN PROBLEMA EN LA ACTUALIZACIÓN");
                }
                
                if (txtPassword1.getPassword().length > 0 && txtPassword2.getPassword().length > 0) {
                    if (!(Arrays.equals(txtPassword1.getPassword(), txtPassword2.getPassword()))) {
                        JOptionPane.showMessageDialog(null, "LAS CONTRASEÑAS NO COINCIDEN");
                    } else {

                    }
                }

            }
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbComunaCom;
    private javax.swing.JComboBox cbComunaPart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbnFemenino;
    private javax.swing.JRadioButton rbnMasculino;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccioncomercial;
    private javax.swing.JTextField txtDireccionparticular;
    private javax.swing.JTextField txtDv;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumerocomercial;
    private javax.swing.JTextField txtNumeroparticular;
    private javax.swing.JPasswordField txtPassword1;
    private javax.swing.JPasswordField txtPassword2;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
