/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controller.DatosProdControlador;
import Controller.HistorialVentasControlador;
import Controller.ProductorControlador;
import DAO.ProductorDAO;
import DTO.Productor;
import java.awt.print.PrinterException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import DTO.Historial_ventas;
import DTO.Usuario;
import java.text.MessageFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTable;


/**
 *
 * @author Francisco
 */
public class HistorialVentasProd extends javax.swing.JFrame {

    ProductorControlador prc = new ProductorControlador();
    DatosProdControlador dpc = new DatosProdControlador();
    HistorialVentasControlador hvc = new HistorialVentasControlador();
    DefaultComboBoxModel modelListaProductores = new DefaultComboBoxModel(prc.listaProductores().toArray());
    Productor prod = new Productor();

    
    /**DefaultComboBoxModel modelListaProductores = new DefaultComboBoxModel(prc.listaProductores().toArray());
     * Creates new form Historial_ventas
     * @param usu
     */
    public HistorialVentasProd(Usuario usu) {
        initComponents();
        
      ArrayList<Productor> arrpro = prc.listaProductores();
//      for(int i =0;i<arrpro.size();i++){
//          cmbListarproductores.addItem(arrpro.get(i));
//      }
      prod = dpc.getProductor(usu.getRut());
        this.fillTable(prod.getRut());
        this.setTitle("HISTORIAL DE VENTAS "+ prod.getNombre()+ " "+prod.getApellido());
        lblNombre.setText(prod.getNombre()+ " "+prod.getApellido());
        tbVentas.setAutoCreateRowSorter(true);
        tbVentas.getTableHeader().setReorderingAllowed(false);
    }   

//    Nombre del producto
//Tipo (Es el tipo de producto)
//Tipo de unidad
//Precio (Es el precio por unidad)
//Cantidad (Es la cantidad comprada)
//Precio Final
//N° de venta
//Cliente

    String col[] = {"Nombre Producto", "Tipo de Producto", "Tipo de Unidad", "Precio Unitario", "Cantidad", "Total", "Nº Venta", "Cliente"};
    DefaultTableModel tablemodel = new DefaultTableModel(col, 0);
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVentas = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("VENTAS");

        tbVentas.setModel(tablemodel);
        jScrollPane1.setViewportView(tbVentas);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(244, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 424, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimir)
                    .addComponent(btnVolver))
                .addGap(28, 28, 28))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(103, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // Cierra la ventana y vuelve al menú:
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
       try {
            // Imprime la tabla:
            MessageFormat header = new MessageFormat("Ventas "+ prod.getNombre()+ " " +prod.getApellido());
            MessageFormat footer = new MessageFormat("Page {0,number,integer}");
            tbVentas.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException ex) {
            Logger.getLogger(ManProductosProductor.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void fillTable(String rut) {
        // Llena la tabla. Por ahora el contenido no incluye los nombres, sólo IDs.
        if (hvc.listaVentas(rut).size() > 0) {
            for (int i = 0; i < hvc.listaVentas(rut).size(); i++) {
                Historial_ventas vent = hvc.listaVentas(rut).get(i);
                String[] linea = {vent.getNombre_producto(),
                    vent.getTipo_producto(),
                    vent.getTipo_unidad(),
                    vent.getPrecio_unitario(),
                    vent.getCantidad(),
                    vent.getPrecio_final(),
                    vent.getNum_venta(),
                    vent.getNombre_cliente()
                };
                tablemodel.addRow(linea);
            }
        }
        }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTable tbVentas;
    // End of variables declaration//GEN-END:variables
}
