/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controller.DatosProdControlador;
import DAO.ProductoDAO;
import DTO.Producto;
import DTO.Productor;
import DTO.Usuario;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Francisco
 */
public class ManProductosProductor extends javax.swing.JFrame {

    DatosProdControlador dpc = new DatosProdControlador();
    Productor pro = new Productor();
    String col[] = {"Id", "Producto", "Descripción", "Oferta", "Tipo Cultivo", "Tipo Unidad", "Precio U"};
    DefaultTableModel tablemodel = new DefaultTableModel(col, 0);
    ProductoDAO pdao = new ProductoDAO();

    /**
     * Creates new form ManProductosProductor
     */
    public ManProductosProductor(Usuario usu) {
        initComponents();
        pro = dpc.getProductor(usu.getRut());
        //Llamada a método que llena la tabla:
        this.fillTable(Integer.parseInt(usu.getRut()));
        //Sólo se puede seleccionar un valor de la tabla.
        tbProductos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    private void fillTable(int rut) {
        // Llena la tabla. Por ahora el contenido no incluye los nombres, sólo IDs.
        if (pdao.listaProductosRUT(rut).size() > 0) {
            for (int i = 0; i < pdao.listaProductosRUT(rut).size(); i++) {
                Producto prod = pdao.listaProductosRUT(rut).get(i);
                String[] linea = {Integer.toString(prod.getId_producto()),
                    Integer.toString(prod.getId_tipo_producto()),
                    prod.getDescripcion(),
                    Integer.toString(prod.getOferta()), Integer.toString(prod.getId_tipo_cultivo()),
                    Integer.toString(prod.getId_medida()), Integer.toString(prod.getPrecio())
                };
                tablemodel.addRow(linea);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbProductos = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbProductos.setModel(tablemodel);
        jScrollPane1.setViewportView(tbProductos);

        btnModificar.setText("Ver Detalles/Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimir)
                    .addComponent(btnAgregar)
                    .addComponent(btnModificar))
                .addGap(18, 18, 18)
                .addComponent(btnVolver)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // Cierra la ventana y vuelve al menú:
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        try {
            // Imprime la tabla:
            tbProductos.print();
        } catch (PrinterException ex) {
            Logger.getLogger(ManProductosProductor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // Pasa el objeto producto a la ventana de edición:
        int id = tbProductos.getSelectedRow();
        int val = Integer.parseInt(tbProductos.getModel().getValueAt(id, 0).toString());
        Producto prod = pdao.getProducto(val);
        EditorProducto ep = new EditorProducto(prod);
        ep.setVisible(true);
        ep.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbProductos;
    // End of variables declaration//GEN-END:variables
}
