/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controller.DatosProdControlador;
import Controller.VentanaPrincipalControlador;
import DAO.ParametroDAO;
import DTO.InactivityListener;
import DTO.Parametro;
import DTO.Productor;
import DTO.Usuario;
import DTO.UsuarioLogin;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JFrame;

/**
 *
 * @author Jorge
 */
public class Ventana_Principal extends javax.swing.JFrame {

    InactivityListener listener;
    DatosProdControlador dpc = new DatosProdControlador();
    VentanaPrincipalControlador vpc = new VentanaPrincipalControlador();
    ParametroDAO pardao = new ParametroDAO();
    Parametro timeout = pardao.getParametro(2);
    UsuarioLogin ulog = new UsuarioLogin();

    /**
     * Creates new form Ventana_Principal
     * @param usu Datos del usuario
     * @param log Datos de la sesión
     */
    public Ventana_Principal(Usuario usu, UsuarioLogin log) {
        initComponents();
        ulog = log;
        Productor p = dpc.getProductor(usu.getRut());
        lblUsuario.setText("Bienvenido " + p.getNombre() + " " + p.getApellido());
        listener = new InactivityListener(this, logout, Integer.parseInt(timeout.getValor1()));
        listener.start();

    }

    Action logout = new AbstractAction() {

        @Override
        public void actionPerformed(ActionEvent ae) {
            JFrame frame = (JFrame) ae.getSource();
            vpc.borrarLogin(ulog);
            System.exit(0);

        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        btnListarProductores = new javax.swing.JButton();
        btnInformedeVentas = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVolver.setText("Salir");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Feria Web Menú");

        btnListarProductores.setText("Listar productores");
        btnListarProductores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarProductoresActionPerformed(evt);
            }
        });

        btnInformedeVentas.setText("Ver Historial de Venta");
        btnInformedeVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformedeVentasActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar Sesión");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(274, Short.MAX_VALUE)
                        .addComponent(btnVolver)))
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInformedeVentas, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(btnListarProductores, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnListarProductores)
                .addGap(18, 18, 18)
                .addComponent(btnInformedeVentas)
                .addGap(18, 18, 18)
                .addComponent(btnCerrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // Cierra el programa
        vpc.borrarLogin(ulog);
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnListarProductoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarProductoresActionPerformed
        // Botón para ir a página de lista de productores
        Listar_Productores lp = new Listar_Productores(ulog);
        lp.setVisible(true);
        lp.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnListarProductoresActionPerformed

    private void btnInformedeVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformedeVentasActionPerformed
        // TODO add your handling code here:
        Historialventas hventas = new Historialventas(ulog);
        hventas.setVisible(true);
        hventas.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnInformedeVentasActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        vpc.borrarLogin(ulog);
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnInformedeVentas;
    private javax.swing.JButton btnListarProductores;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
