
package localhost.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServicePruebaSoap", targetNamespace = "http://localhost/WebService")
@XmlSeeAlso({
    localhost.webservice.ObjectFactory.class,
    org.w3._2001.xmlschema.ObjectFactory.class
})
public interface WebServicePruebaSoap {


    /**
     * 
     * @param pas
     * @param user
     * @return
     *     returns localhost.webservice.AutenticarResponse.AutenticarResult
     */
    @WebMethod(operationName = "Autenticar", action = "http://localhost/WebService/Autenticar")
    @WebResult(name = "AutenticarResult", targetNamespace = "http://localhost/WebService")
    @RequestWrapper(localName = "Autenticar", targetNamespace = "http://localhost/WebService", className = "localhost.webservice.Autenticar")
    @ResponseWrapper(localName = "AutenticarResponse", targetNamespace = "http://localhost/WebService", className = "localhost.webservice.AutenticarResponse")
    public localhost.webservice.AutenticarResponse.AutenticarResult autenticar(
        @WebParam(name = "user", targetNamespace = "http://localhost/WebService")
        String user,
        @WebParam(name = "pas", targetNamespace = "http://localhost/WebService")
        String pas);

    /**
     * 
     * @return
     *     returns localhost.webservice.RegionesResponse.RegionesResult
     */
    @WebMethod(operationName = "Regiones", action = "http://localhost/WebService/Regiones")
    @WebResult(name = "RegionesResult", targetNamespace = "http://localhost/WebService")
    @RequestWrapper(localName = "Regiones", targetNamespace = "http://localhost/WebService", className = "localhost.webservice.Regiones")
    @ResponseWrapper(localName = "RegionesResponse", targetNamespace = "http://localhost/WebService", className = "localhost.webservice.RegionesResponse")
    public localhost.webservice.RegionesResponse.RegionesResult regiones();

    /**
     * 
     * @param idregion
     * @return
     *     returns localhost.webservice.ComunasResponse.ComunasResult
     */
    @WebMethod(operationName = "Comunas", action = "http://localhost/WebService/Comunas")
    @WebResult(name = "ComunasResult", targetNamespace = "http://localhost/WebService")
    @RequestWrapper(localName = "Comunas", targetNamespace = "http://localhost/WebService", className = "localhost.webservice.Comunas")
    @ResponseWrapper(localName = "ComunasResponse", targetNamespace = "http://localhost/WebService", className = "localhost.webservice.ComunasResponse")
    public localhost.webservice.ComunasResponse.ComunasResult comunas(
        @WebParam(name = "idregion", targetNamespace = "http://localhost/WebService")
        int idregion);

    /**
     * 
     * @param rut
     * @param dv
     * @param apellido
     * @param correo
     * @param sexo
     * @param telefono
     * @param idComuna
     * @param nombre
     * @param idDireccionparticular
     */
    @WebMethod(action = "http://localhost/WebService/registrarCliente")
    @RequestWrapper(localName = "registrarCliente", targetNamespace = "http://localhost/WebService", className = "localhost.webservice.RegistrarCliente")
    @ResponseWrapper(localName = "registrarClienteResponse", targetNamespace = "http://localhost/WebService", className = "localhost.webservice.RegistrarClienteResponse")
    public void registrarCliente(
        @WebParam(name = "rut", targetNamespace = "http://localhost/WebService")
        int rut,
        @WebParam(name = "dv", targetNamespace = "http://localhost/WebService")
        int dv,
        @WebParam(name = "nombre", targetNamespace = "http://localhost/WebService")
        String nombre,
        @WebParam(name = "apellido", targetNamespace = "http://localhost/WebService")
        String apellido,
        @WebParam(name = "sexo", targetNamespace = "http://localhost/WebService")
        int sexo,
        @WebParam(name = "correo", targetNamespace = "http://localhost/WebService")
        String correo,
        @WebParam(name = "telefono", targetNamespace = "http://localhost/WebService")
        int telefono,
        @WebParam(name = "id_direccionparticular", targetNamespace = "http://localhost/WebService")
        int idDireccionparticular,
        @WebParam(name = "id_comuna", targetNamespace = "http://localhost/WebService")
        int idComuna);

}
